# Generated by Django 2.2.5 on 2019-10-03 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Precio')),
                ('npo', models.BooleanField(default=False, verbose_name='Dieta para pacientes NPO')),
                ('dieta_personal', models.BooleanField(default=False, verbose_name='Dieta para personal')),
            ],
            options={
                'verbose_name': 'dieta',
                'verbose_name_plural': 'dietas',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
            ],
            options={
                'verbose_name': 'jornada',
                'verbose_name_plural': 'jornadas',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'tipo_personal',
                'verbose_name_plural': 'tipos_de_personal',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta_viaje', models.BooleanField(default=False, verbose_name='¿Dieta de Viaje?')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dieta_jornada', to='catalogos.Jornada', verbose_name='Jornada')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_personal', to='catalogos.Personal', verbose_name='Personal')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_servicio', to='catalogos.Servicio', verbose_name='Servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dieta_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'solicitud_dieta',
                'verbose_name_plural': 'solicitudes_de_dieta',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_tipo', to='catalogos.TipoPersonal', verbose_name='Tipo de Personal'),
        ),
        migrations.CreateModel(
            name='DetalleSolicitudDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('precio', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Precio')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_dieta', to='catalogos.Dieta', verbose_name='Dieta')),
                ('solicitud_dieta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_solicitud', to='catalogos.SolicitudDieta', verbose_name='Solicitud de Dieta No.')),
            ],
            options={
                'verbose_name': 'detalle_solicitud',
                'verbose_name_plural': 'detalles_solicitud',
            },
        ),
    ]
