# Generated by Django 2.2.5 on 2019-10-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicituddieta',
            name='no_cama',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18, verbose_name='No. de cama'),
            preserve_default=False,
        ),
    ]
