# Generated by Django 2.2.5 on 2019-10-04 23:20

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_NoDeCamaSolicitudDieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicituddieta',
            name='created',
        ),
        migrations.RemoveField(
            model_name='detallesolicituddieta',
            name='modified',
        ),
        migrations.AddField(
            model_name='solicituddieta',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicituddieta',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
