# Generated by Django 2.2.5 on 2019-10-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_CambiadoTimeStampModel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicituddieta',
            name='no_cama',
            field=models.IntegerField(verbose_name='No. de cama'),
        ),
    ]
