# Generated by Django 2.2.5 on 2019-11-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_CambiadoTipoNoCama'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddieta',
            name='servida',
            field=models.BooleanField(default=False, verbose_name='Dieta Servida'),
        ),
        migrations.AddField(
            model_name='solicituddieta',
            name='total_dietas_servidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de dietas Servidas'),
        ),
        migrations.AlterField(
            model_name='solicituddieta',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_personal', to='catalogos.Personal', verbose_name='Personal*'),
        ),
        migrations.AlterField(
            model_name='solicituddieta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_servicio', to='catalogos.Servicio', verbose_name='Servicio*'),
        ),
    ]
