# Generated by Django 2.2.5 on 2019-11-02 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0005_CamposNuevosSolicitudDieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddieta',
            name='usuario_sirvio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_usuario_sirvio', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Sirvio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicituddieta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dieta_usuario_registro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registro'),
        ),
    ]
