# Generated by Django 2.2.5 on 2019-12-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_CamposUsuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicituddieta',
            name='precio',
        ),
        migrations.AddField(
            model_name='detallesolicituddieta',
            name='especificar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especificar'),
        ),
        migrations.AlterField(
            model_name='detallesolicituddieta',
            name='no_cama',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. de cama'),
        ),
    ]
