# Generated by Django 2.2.5 on 2019-12-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_CambiadoCamposDetalleSolicitudDieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='precio',
        ),
    ]
