# Generated by Django 2.2.5 on 2019-12-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_QuitadoPrecioDieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddieta',
            name='dieta_viaje',
        ),
        migrations.RemoveField(
            model_name='solicituddieta',
            name='personal',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='TipoPersonal',
        ),
    ]
