# Generated by Django 2.2.5 on 2019-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_LimpiezaModelos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='dieta_personal',
        ),
        migrations.AddField(
            model_name='dieta',
            name='viaje',
            field=models.BooleanField(default=False, verbose_name='Dieta de viaje'),
        ),
    ]
