# Generated by Django 2.2.5 on 2020-01-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0010_ActualizadoModeloDietas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDietaTiempoEstablecido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_dietas_a_solicitar', models.PositiveIntegerField(verbose_name='No. de dietas a solicitar')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_dieta_tiempo_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'solicitud_dieta_tiempo_establecido',
                'verbose_name_plural': 'solicitudes_dietas_tiempo_establecido',
            },
        ),
    ]
