# Generated by Django 2.2.5 on 2020-01-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_AgregadoModeloSolicitudDietaTiempoEstablecido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddieta',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dieta_servicio', to='catalogos.Servicio', verbose_name='Servicio*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicituddietatiempoestablecido',
            name='no_dietas_a_solicitar',
            field=models.PositiveIntegerField(verbose_name='No. de solicitudes de dietas'),
        ),
    ]
