# Generated by Django 2.2.5 on 2020-03-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_ServicioRequerido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicituddieta',
            name='no_cama',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. de cama'),
        ),
        migrations.AlterField(
            model_name='solicituddieta',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dieta_servicio', to='catalogos.Servicio', verbose_name='Servicio'),
        ),
    ]
